### ISSUE TITLE
Tile path calculation wrong on iOS 13

### ISSUE THREAD

**Issue by staykids** [wdtinc/SkywiseTilesDemo-iOS#4]
It appears there's a bug with calculating tile paths on iOS 13. It looks like every other X and Y tile in the sequence is getting skipped. This results in dramatically incorrect renderings. Take a look at these example screenshots from iOS 12.4 and iOS 13.0 with the debugging turned on.

![ios12_paths](https://user-images.githubusercontent.com/5652327/65395236-f5a51300-dd4c-11e9-8ad0-f817e929d2dc.png)
![ios13_paths](https://user-images.githubusercontent.com/5652327/65395237-f5a51300-dd4c-11e9-93ba-160fd2fa5bca.png)

Targeting iOS 12.4 (light color map), you can see the sequence properly increasing (6/15/22, 6/16/22 - 6/15/23, 6/16/23), but targeting iOS 13.0 (dark color map), you can see the horizontal and vertical sequence skipping the proper next elements (6/15/21, 6/17/22 - 6/15/23, 6/17/23).

This weird skipping only appears to affect X and Y calculations, and again, only on iOS 13+. Z calculations appear to be unaffected. It seems something is off with the `SwarmHelpers`'s `pathForZoom(...)` and `tilePaths(...)` on the `MKMapRect` extension, but I could certainly be wrong.

EDIT: Resolved. Thanks!

**Comment by rosskimes** [comment]
Have you tried this with the [ios13 branch](https://github.com/wdtinc/SkywiseTilesDemo-iOS/tree/ios13)?

**Comment by staykids** [comment]
> Have you tried this with the [ios13 branch](https://github.com/wdtinc/SkywiseTilesDemo-iOS/tree/ios13)?

Oh awesome. My bad – I did not notice that branch before posting. Sorry for wasting your time.
